### ISSUE TITLE
Login fails using chrome

### ISSUE THREAD

**Issue by quba** [FriendsOfSymfony/FOSFacebookBundle#102]
Can anybody confirm, that this bundle works well using chrome (or chromium)? My implementation is little bit different because of using FosUserBundle. It's strange, because everything works great on firefox, opera and konqueror. Chromium's errors returned by the bundle:
`The Facebook user could not be retrieved from the session.`
Chrome's javascript console:
http://paste.org/43694
Firewall configuration:

``` yaml
firewalls:
        public:
            pattern: ^/
            openid: true
            form_login:
                provider: fos_userbundle
                login_path: /login
                always_use_default_target_path: true
                default_target_path: /login
            fos_facebook:
                login_path: /login
                check_path: /facebook/login_check
                default_target_path: /login
                provider: my_fos_facebook_provider
            logout:
                target: /login
            anonymous: ~
```

js login action:
http://paste.org/43693

If you think it's fosfacebook+fosuser issue and not ony fosfacebook, just close it. 

Due to this error I've switched to php-sdk.
