### ISSUE TITLE
Error FOSFacebookBundle

### ISSUE THREAD

**Issue by Raulken** [FriendsOfSymfony/FOSFacebookBundle#118]
Unrecognized options "fos_facebook" under "security.firewalls.public"

what i wrog?

config.yml:

fos_facebook:
      file:   %kernel.root_dir%/../vendor/facebook/src/base_facebook.php
      alias:  facebook
      app_id: 123456879
      secret: s3cr3t
      cookie: true
      permissions: [email, user_birthday, user_location]

security:
      providers:
          # choose the provider name freely
          my_fos_facebook_provider:
              id: my.facebook.user   # see "Example Custom User Provider using the FOS\UserBundle" chapter further down

```
  firewalls:
      public:
          pattern:   ^/.*
          fos_facebook:
              app_url: "http://apps.facebook.com/appName/"
              server_url: "http://localhost/facebookApp/"
              login_path: ^/login
              check_path: ^/login_check$
              default_target_path: /
              provider: my_fos_facebook_provider
          anonymous: true
          logout:
              handlers: ["fos_facebook.logout_handler"]

  access_control:
      - { path: ^/secured/.*, role: [IS_AUTHENTICATED_FULLY] } # This is the route secured with fos_facebook
      - { path: ^/facebook/,           role: [ROLE_FACEBOOK] }
      - { path: ^/.*, role: [IS_AUTHENTICATED_ANONYMOUSLY] }
```
