### ISSUE TITLE
Security with FacebookBundle

### ISSUE THREAD

**Issue by dator-zz** [FriendsOfSymfony/FOSFacebookBundle#13]
Hi,

I tried to use FacebookBundle in a app, i put all the default configuration but i change the security part like that:

```
security:
     factories:
         -"%kernel.root_dir%/../src/FOS/FacebookBundle/Resources/config/security_factories.xml"

     providers:
          fos_facebook:
          id: fos_facebook.auth

    firewalls:
        only_facebook: # with facebook entry point (redirect to the facebook login url)
            pattern:   /.*
            fos_facebook:  true

    access_control:
        - { path: /.*, role: [ROLE_USER] }
```

According to the documentation, if an user is not logedin to the app, he will be redirected to the login url, but it's doesnt the case. I get an Access Denied exception

Anyone has an idea ? 
Thanks a lot :)
