### ISSUE TITLE
Authentication Entry Point does not work (configured?) well

### ISSUE THREAD

**Issue by Koc** [FriendsOfSymfony/FOSFacebookBundle#133]
Looks like Entry Point does not work well.

``` yml
            fos_facebook:
                login_path: /user/auth/form
                check_path: /user/auth-facebook/identify
                success_handler: ololo.users.security.success_handler
                provider: fos_facebook_entity
```

```
Symfony\Component\DependencyInjection\Compiler\RemoveUnusedDefinitionsPass: Removed service "fos_facebook.security.authentication.entry_point.main"; reason: unused
```

When I open /user/auth-facebook/identify got an error "The Facebook user could not be retrieved from the session.". But I should be redirected to login url.
