### ISSUE TITLE
Documentaion

### ISSUE THREAD

**Issue by vazgen** [FriendsOfSymfony/FOSFacebookBundle#148]
Hello, thanks for this bundle. In my project I have SonataAdminBundle + FosUserBundle that work great. But it is very difficult to integrate this one, so spend last two days without result. 

Is there any good documentation how to user FosUserBundle + FosFacebookBundle? (I have googled a lot, and read this documentation few times)

thanks

**Comment by lsmith77** [comment]
this is a semi decent example using LiipHelloBundle to illustrate things: https://github.com/lsmith77/symfony-standard/tree/techtalk

**Comment by vazgen** [comment]
yeah, thanks for replay. Actually I had tried it before reporting this issue. It has a bug in user login (not by facebook)

this page works: http://symfony-standard.lo/app_dev.php/liip/facebook
but this one does not: http://symfony-standard.lo/app_dev.php/liip/login

after I enter username and password and push submit it get me an error
"You must configure the check path to be handled by the firewall using form_login in your security firewall configuration."

but I see check path in security.yml

```
main:
           pattern:   ^/liip/
           form_login:
               login_path: /login
               check_path: /login-check
           provider: fos_userbundle

        fos_facebook:
            login_path: /liip/facebook
            check_path: /liip/facebook-check
            default_target_path: /liip/facebook
            provider: fos_facebook
```
