### ISSUE TITLE
Can't access the user in security.context when logged in 

### ISSUE THREAD

**Issue by hosseio** [FriendsOfSymfony/FOSFacebookBundle#155]
Hi.

When accessing the security.context for the token when logged always return an "anonymous user".
It works when accessing a secure page (under access_control security section) with ROLE_ADMIN, ROLE_USER or similar. But I need the user (in case there is one) in pages where you can access anonymously.

Any thoughts?

Thanks in advance.

**Comment by stof** [comment]
paste your security config please

**Comment by hosseio** [comment]
Thank you for your response.
Here is my security config:

``` yaml
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        "FOS\UserBundle\Model\UserInterface": sha512

    providers:
        fos_user:
            id: fos_user.user_manager
        fos_facebook:
            id: my.facebook.user

    factories:
        - "%kernel.root_dir%/../vendor/bundles/FOS/FacebookBundle/Resources/config/security_factories.xml"

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        public:
            pattern: ^/.*
            fos_facebook:
                app_url: "http://apps.facebook.com/restauranting/"
                server_url: "http://localhost/"
                login_path: /login
                check_path: /login_check$
                default_target_path: /
                provider: fos_facebook
            logout:
                handlers: ["fos_facebook.logout_handler"]
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/.*, role: [IS_AUTHENTICATED_ANONYMOUSLY] }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
```

Debugging  it I am seeing the listener (FacebookListener) is never invoke, so the token is never setted in AbstractAuthenticationListener

Regards.
