### ISSUE TITLE
error for installation dev-master version

### ISSUE THREAD

**Issue by Raulken** [FriendsOfSymfony/FOSFacebookBundle#191]
sudo php composer.phar update friendsofsymfony/facebook-bundle

Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - friendsofsymfony/facebook-bundle 2.0.x-dev requires facebook/php-sdk dev-master -> satisfiable by facebook/php-sdk dev-master.
    - friendsofsymfony/facebook-bundle dev-master requires facebook/php-sdk dev-master -> satisfiable by facebook/php-sdk dev-master.
    - facebook/php-sdk dev-master requires ext-curl \* -> no matching package found.
    - Installation request for friendsofsymfony/facebook-bundle \* -> satisfiable by friendsofsymfony/facebook-bundle 2.0.x-dev, friendsofsymfony/facebook-bundle dev-master.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

any idea?

**Comment by Baachi** [comment]
`facebook/php-sdk dev-master requires ext-curl * -> no matching package found.`
You need the cURL extension ;-)

**Comment by Chrysweel** [comment]
Yes, I had the same problem. 
And I did : " sudo apt-get install php5-curl"  and it works! 
Thanks Baachi!

**Comment by Raulken** [comment]
thxxxx yeah now download

i have make all configuration with documentation...and....another error ^^

Fatal error: JMS\AopBundle\DependencyInjection\Compiler\PointcutMatchingPass::processDefinition(): Failed opening required '/home/ubuntu/NetBeansProjects/PhpProject8/app/../vendor/facebook/src/base_facebook.php' (include_path='.:/usr/share/php:/usr/share/pear') in /home/ubuntu/NetBeansProjects/PhpProject8/vendor/jms/aop-bundle/JMS/AopBundle/DependencyInjection/Compiler/PointcutMatchingPass.php on line 93 

.....but i not understand what is this....help? thx

**Comment by Baachi** [comment]
Please read the error message :)

```
Failed opening required '/home/ubuntu/NetBeansProjects/PhpProject8/app/../vendor/facebook/src/base_facebook.php' 
```

If you use composer to autoload your classes, you can remove the file key in your configuration file.

**Comment by Raulken** [comment]
i have change this
fos_facebook:
      file:   %kernel.root_dir%/../vendor/facebook/php-sdk/src/base_facebook.php

now work....only not record my login in database

and if i make normal login with sonata they say

**Comment by Raulken** [comment]
i have change this

``` yaml
fos_facebook:
      file:   %kernel.root_dir%/../vendor/facebook/php-sdk/src/base_facebook.php
```

now work....only not record my login in database

and if i make normal login with sonata they say
  The Facebook user could not be retrieved from the session

``` html+jinja
<body>
      <!-- inside a twig template -->
      {{ facebook_initialize({'xfbml': true, 'fbAsyncInit': 'onFbInit();'}) }}
      <!-- inside a twig template -->
{{ facebook_login_button({'autologoutlink': true}) }}


      <script>
  function goLogIn(){
      window.location = "{{ path('_security_check') }}";
  }

  function onFbInit() {
      if (typeof(FB) != 'undefined' && FB != null ) {
          FB.Event.subscribe('auth.statusChange', function(response) {
              if (response.session || response.authResponse) {
                  setTimeout(goLogIn, 500);
              } else {
                  window.location.href = "{{ path('_security_logout') }}";
              }
          });
      }
  }
</script>
```

``` yaml
acme_welcome:
    resource: "@AcmeWelcomeBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /profile

sonata_user_profile:
    resource: "@SonataUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

_security_check:
      pattern:  /login_check
_security_logout:
      pattern:  /logout
```
