### ISSUE TITLE
login facebook are ok but...

### ISSUE THREAD

**Issue by Raulken** [FriendsOfSymfony/FOSFacebookBundle#196]
if I login with facebook button works, I registered in the database, I recorded my logs and my facebookid
but when I try to login with a normal user tells me
  The Facebook user could not be retrieved from the session

why?

**Comment by stof** [comment]
you should be using different check paths for the form login and the facebook login. Otherwise, the facebook login would be triggered when submitting the form, which indeed breaks.

**Comment by Chrysweel** [comment]
How did you get this to work?

I log to facebook from my localhost, but when I access to page with role IS_AUTHENTICATED_FULLY, I am redirecting to page of login.

And when a user register in my project, the facebookId of my database  is null. And when log in facebook from my web, nothing is record in my database.

My code is:

I use symfony2.1.3-dev.
My config.yml is:

```
fos_facebook:
    file: %kernel.root_dir%/../vendor/facebook/php-sdk/src/base_facebook.php
    alias: facebook
    app_id: myappid
    secret: mysecret
    cookie: true
    permissions: [email, user_birthday, user_location]
services:
    my.facebook.user:
        class: project\myBundle\Security\User\Provider\FacebookProvider
        arguments:
            facebook: "@fos_facebook.api"
            userManager: "@fos_user.user_manager"
```

routing.yml

```
#FosFacebookBundle
_security_check:
      pattern:  /login_check_fb
_security_logout:
      pattern:  /logout
_facebook_secured:
    pattern: /secured/{nombre}
    defaults: { _controller: myBundle:Default:estatica}
```

security.yml

```
providers:
        chain_provider:
            chain:
                providers: [fos_userbundle, my_fos_facebook_provider]
        fos_userbundle:
            id: fos_user.user_provider.username
        my_fos_facebook_provider:
              id: my.facebook.user
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            switch_user: true
            context: user
            pattern: /admin(.*)
            form_login:
                provider: fos_userbundle
                login_path: /admin/login
                use_forward: false
                check_path: /admin/login_check
                failure_path: null
                use_referer: true #redirige al usuario a la pagina que venia antes de hacer login
            logout:
                path: /admin/logout
                target: / #url a la que va a ir despues de logout

            anonymous: true
       main:
            pattern: ^/*
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            fos_facebook:
                app_url: "http://apps.facebook.com/subireventos/"
                server_url: "http://localhost/workspace/web/app_dev.php/"
                login_path: /login
                check_path: /login_check_fb
                provider: my_fos_facebook_provider
            logout:
                handlers: ["fos_facebook.logout_handler"]
            anonymous:    true

access_control:
        #FOSFacebookBundle
        - { path: ^/secured/.*, role: IS_AUTHENTICATED_FULLY }        
        - { path: ^/publicar/*, roles: ROLE_USER }
        #SonataUser
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #SonataUserBundle
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login-check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_USER }
```

In my base.html.twig I included:

```
{{ facebook_initialize({'xfbml': true, 'fbAsyncInit': 'onFbInit();'}) }}
```

And in one of the page of login(FOSUserBundle) included: ( with this line code, the user can log on facebook, from my web)

```
{{ facebook_login_button({'autologoutlink': true}) }}
<script>
  function goLogIn(){
      window.location.href = "{{ path('_security_check') }}";
  }

  function onFbInit() {
      if (typeof(FB) != 'undefined' && FB != null ) {
          FB.Event.subscribe('auth.statusChange', function(response) {
              if (response.session || response.authResponse) {
                  setTimeout(goLogIn, 500);
              } else {
                  window.location.href = "{{ path('_security_logout') }}";
              }
          });
      }
  }
</script>
```

HELP ME PLEASE ! ; )

**Comment by Raulken** [comment]
@Chrysweel you must test your project online
offline never have work to me...your code is very similar to me.......only i use sonata  fosuser and fosfacebook very caos :D

**Comment by Raulken** [comment]
@stof  i not understand can u make one exaple?please
thx

**Comment by Raulken** [comment]
if i set 
check_path: /login_checkFB  for facebook
check_path:     /login_check  for login normal

``` yaml
    public:
              pattern:   ^/.*
              fos_facebook:
                  app_url: "http://apps.facebook.com/myid/"
                  server_url: "mysite"
                  login_path: /login
                  check_path: /login_checkFB
                  default_target_path: /
                  provider: my_fos_facebook_provider
              anonymous: true
              logout:
                path: fos_user_security_logout    
                target: /

        main:
            switch_user:        true
            context:            user
            pattern:            .*
            form_login:
                provider:       fos_userbundle
                login_path:     /login
                use_forward:    false
                check_path:     /login_check
                failure_path:   null
            logout:             true
            anonymous:          true
```

and in rounting 
_security_check:
      pattern:  /login_checkFB
_security_logout:
      pattern:  /logout

if i make normal login with my superadmin account return this error:
RuntimeException: You must configure the check path to be handled by the firewall using form_login in your security firewall configuration.

but it is configureted..... :D can u help?
