### ISSUE TITLE
Login with FOSFacebookBundle and userstorage with FOSUserBundle - last hints needed ;)

### ISSUE THREAD

**Issue by ghost** [FriendsOfSymfony/FOSFacebookBundle#197]
I have a problem very similar to this of Raulken.
My application do a FB-login with fosfacebookbundle and store the data with fosuserbundle. right now i can login with fb-button and the userdata is stored in database correctly.

But the developerbar always tell me "Logged in as anon. Authenticated Yes". How can i access the logged-in user from inside my controller?

The second problem is, that my protected route is /game but in the url there is always /login loaded (the template for game is rendered correctly). Did i understand that right, that i dont need a particular login-action?

here is my code:

config.yml

```
# FOSFacebookBundle Configuration
fos_facebook:
      file:   %kernel.root_dir%/../vendor/facebook/src/base_facebook.php
      alias:  facebook
      app_id: %facebookAppId%
      secret: %facebookAppSecret%
      cookie: true
      permissions: [email, user_birthday]

# FOSUserBundle Configuration      
fos_user:
    db_driver: orm
    firewall_name: public
    user_class: X\YBundle\Entity\User
```

security.yml

```
services:
       my.facebook.user:
           class: X\YBundle\Security\FacebookUserProvider
           arguments:
               facebook: "@fos_facebook.api"
               userManager: "@fos_user.user_manager"
               validator: "@validator"
               container: "@service_container"

security:
    providers:
        my_fos_facebook_provider:
            id: my.facebook.user

    firewalls:
        public:
            pattern:   ^/.*
            fos_facebook:
                app_url: "https://www.facebook.com/apps/application.php?id=%facebookAppId%"
                server_url: "http://localhost/web/_repositories/x/web/app_dev.php/"
                provider: my_fos_facebook_provider
                default_target_path: /game
            anonymous: true
            logout:
                handlers: ["fos_facebook.logout_handler"]

    access_control:
        - { path: ^/game, roles: ROLE_FACEBOOK }
```

PageController.php

```
<?php

namespace X\YBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;

class PageController extends Controller
{
    /**
     * @Route("/", name="_index")
     * @Template()
     */
        public function indexAction()
    {
        return array('facebookAppId' => $this->container->getParameter('facebookAppId'));
    }

    /**
     * @Route("/game", name="_game")
     * @Template()
     */
        public function gameAction()
    {
        // this is the protected route where the game-template is rendered
        return array('facebookAppId' => $this->container->getParameter('facebookAppId'));
    }

    /**
     * @Route("/login", name="_security_login")
     */
        public function loginAction()
    {
                $response = $this->forward('XYBundle:Page:game');
            return $response;
    }

    /**
     * @Route("/login_check", name="_security_check")
     */
        public function loginCheckAction()
    {
      return array();
    }

    /**
     * @Route("/logout", name="_security_logout")
     */
        public function logoutAction()
    {
      return array();
    }
}
```

FacebookUserProvider.php

```
<?php 
namespace X\YBundle\Security;

use Symfony\Component\Security\Core\Exception\UsernameNotFoundException;
use Symfony\Component\Security\Core\Exception\UnsupportedUserException;
use Symfony\Component\Security\Core\User\UserProviderInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use \BaseFacebook;
use \FacebookApiException;

class FacebookUserProvider implements UserProviderInterface
{
     /**
     * @var \Facebook
     */
    protected $facebook;
    protected $userManager;
    protected $validator;

    public function __construct(BaseFacebook $facebook, $userManager, $validator)
    {
        $this->facebook = $facebook;
        $this->userManager = $userManager;
        $this->validator = $validator;
    }

    public function supportsClass($class)
    {
        return $this->userManager->supportsClass($class);
    }

    public function findUserByFbId($fbId)
    {
        return $this->userManager->findUserBy(array('facebookId' => $fbId));
    }

    public function loadUserByUsername($username)
    {
        //load fb data
        try {
            $fbdata = $this->facebook->api('/me');
        } catch (FacebookApiException $e) {
            $fbdata = null;
        }

        $user = $this->userManager->findUserBy(array('username' => $fbdata['email'])); 

        if (!empty($fbdata)) {
            if (empty($user)) {
                $user = $this->userManager->createUser();
                $user->setEnabled(true);
                $user->setPassword(rand(100000,999999));
                //$user->setActive(1);
            }

            // TODO use http://developers.facebook.com/docs/api/realtime
            $user->setFBData($fbdata);

            if (count($this->validator->validate($user, 'Facebook'))) {
                // TODO: the user was found obviously, but doesnt match our expectations, do something smart
                throw new UsernameNotFoundException('The facebook user could not be stored');
            }

            $this->userManager->updateUser($user);
        }

        if (empty($user)) {
            throw new UsernameNotFoundException('The user is not authenticated on facebook');
        }

        return $user;
    }

    public function refreshUser(UserInterface $user)
    {

        $user->setFacebookId($user->getUsername()); 

        if (!$this->supportsClass(get_class($user)) || !$user->getFacebookId()) {
            throw new UnsupportedUserException(sprintf('Instances of "%s" are not supported.', get_class($user)));
        }

        return $this->loadUserByUsername($user->getFacebookId());
    }
}
```

and my javascript

```
function goLogIn(){
    window.location.href = routeSecurityCheck;
}

function onFbInit() {

    if (typeof(FB) != 'undefined' && FB != null ) {
        FB.Event.subscribe('auth.statusChange', function(response) {
            if (response.session || response.authResponse) {
                setTimeout(goLogIn, 500);
            } else {
                window.location.href = routeSecurityLogout;
            }
        });
    }
}
```

I would really appreciate your help! If you need further information, let me know :)
