### ISSUE TITLE
I am obligated to login in my web

### ISSUE THREAD

**Issue by Chrysweel** [FriendsOfSymfony/FOSFacebookBundle#204]
This bundle works it. But I am obligated to login from my web.
I log in page of facebook, but when I visit my web, the button login knows that I am connected in facebook, because the button says "logout", but I can't access my page private with role ROLE_FACEBOOK.

I have to do logout in facebook and connect from my buttom facebook.

Why ??

**Comment by diegoholiveira** [comment]
What is happen is that Facebook JS SDK knows that are you logged, but your symfony 2 application don't know notting about it. Force the user to be redirect to the check_path (defined on your security.yml).

**Comment by Chrysweel** [comment]
@diegoholiveira 
Thanks for to reply.
Still could not solve the problem.

This my security.yml

```
providers:
        chain_provider:
            chain:
                providers: [fos_userbundle, my_fos_facebook_provider]
        fos_userbundle:
            id: fos_user.user_provider.username_email
        my_fos_facebook_provider:
              id: my.facebook.user 
 firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            switch_user: true
            context: user
            pattern: /admin(.*)
            form_login:
                provider: fos_userbundle
                login_path: /admin/login
                use_forward: false
                check_path: /admin/login_check
                failure_path: null
                use_referer: true #redirige al usuario a la pagina que venia antes de hacer login
            logout:
                path: /admin/logout
                target: / 

            anonymous: true
        main:
            pattern: ^/*
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            fos_facebook:
                app_url: "http://apps.facebook.com/subireventos/"
                server_url: "http://localhost/workspace/sdfs2.0/web/app_dev.php/"
                login_path: /login
                check_path: /login_check_fb
                provider: my_fos_facebook_provider
            logout:
            anonymous:    true
```

And my config.yml

```
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: chatea\UsuarioBundle\Entity\User
    registration:
       form:
         type: sdfs_user_registration
    group: 
       group_class: sdfs\sdfsBundle\Entity\Group
    profile:
        form:
            type:               fos_user_profile
            name:               fos_user_profile_form
            validation_groups:  [Authentication]
fos_facebook:

    alias: facebook
    app_id: id
    secret: secret
    cookie: true
    permissions: [email, user_birthday, user_location]
services:
    my.facebook.user:
        class: sdfs\sdfsBundle\Security\User\Provider\FacebookProvider
        arguments:
            facebook: "@fos_facebook.api"
            userManager: "@fos_user.user_manager"
            validator: "@validator"
            container: "@service_container"
```

Can you help me ?

**Comment by diegoholiveira** [comment]
Did you follow this instruction?
https://github.com/FriendsOfSymfony/FOSFacebookBundle/blob/master/Resources/doc/1-basic-usage.md#include-the-login-button-in-your-templates

If you follow it, then post on gist.github.com your javascript that defines
the integration between JS and SF2, and then post the link here.

**Comment by Chrysweel** [comment]
Yes @diegoholiveira I followed it.

I have two url for check:
/login_check the route for default of FOSUserBundle
and /login_check_fb the route for FOSFacebookBundle.

Because If I use the same url for check, so I am in facebook or in my web doesnt it?
But I want be able to keep in both web

In my template I have :

```
<script>
  function goLogIn(){
      window.location.href = "/login_check_fb";
  }

  function onFbInit() {
      if (typeof(FB) != 'undefined' && FB != null ) {
          FB.Event.subscribe('auth.statusChange', function(response) {
              if (response.session || response.authResponse) {
                  setTimeout(goLogIn, 500);
              } else {
                  window.location.href = "/logout";
              }
          });
      }
  }
</script>
```

My routing.yml

```
#FosFacebookBundle
_security_check:
      pattern:  /login_check_fb
_security_logout:
      pattern:  /logout
```

Any idea?
