### ISSUE TITLE
Problem with Facebook login

### ISSUE THREAD

**Issue by ghost** [FriendsOfSymfony/FOSFacebookBundle#234]
I followed the differents steps of FOSFacebookBundle with success but I can't logged me in. I have this message "The Facebook user could not be retrieved from the session."

I have Symfony 2.1.7, Facebook SDK 3.2.0, FOSFB 1.1.0 and FOSUB 1.3.1

Thx :)
# security.yml

```
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        chainprovider:
            chain:
                providers: [fos_userbundle, my_facebook_provider]
        fos_userbundle:
            id: fos_user.user_provider.username
        my_facebook_provider:
            id: myapp.facebook.user

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            fos_facebook:
                app_url: "http://apps.facebook.com/app-myapp/"
                server_url: "http://dev.myapp/"
                login_path: /login
                check_path: /login_fb_check
                default_target_path: /
                provider: my_facebook_provider
            logout:       true
            anonymous:    true 

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
```
# config.yml :

```
services:
    myapp.facebook.user:
        class: MyApp\UserBundle\Security\User\Provider\FacebookProvider
        arguments:
            facebook: "@fos_facebook.api"
            userManager: "@fos_user.user_manager"
            validator: "@validator"
            container: "@service_container"
```
# routing.yml

```
_security_check:
  pattern:  /login_fb_check
_security_logout:
  pattern:  /logout
```
