### ISSUE TITLE
Failing to integrate with custom entity provider

### ISSUE THREAD

**Issue by klaussilveira** [FriendsOfSymfony/FOSFacebookBundle#251]
I have a custom entity provider, formed by a custom `User` entity class and a `UserRepository` that extends the `EntityRepository` class. 

I also have a `FacebookProvider` based on the one available [here](https://github.com/FriendsOfSymfony/FOSFacebookBundle/blob/master/Resources/doc/2-integration-with-fosuserbundle.md). It's modified to communicate with my `UserRepository`.

They're all registered as such: 

```
security:
    providers:
        chain_provider:
            chain:
                providers: [main, fb_provider]
        main:
            entity: { class: AcmeBundle:User, property: username }
        fb_provider:
            id: facebook_user_provider

    firewalls:
        main:
            pattern:    ^/
            form_login:
                provider: main
            logout:     true
            anonymous:  true
            fos_facebook:
                app_url: "http://apps.facebook.com/acme/"
                server_url: "http://acme.dev/app_dev.php/"
                provider: fb_provider
```

Problem is: i want users to login using the normal login form, using the `UserRepository`, instead of Facebook. Facebook is now used everywhere, intercepting the normal login form, instead of issuing proper default User AuthorizationTokens. 

 "The Facebook user could not be retrieved from the session." is shown, since i'm not using the correct provider. How can i work with multiple providers? A Facebook provider for FB logins and my Entity Provider for normal logins?

**Comment by diegoholiveira** [comment]
try to add check_path to your provider configuration, as above:

``` yaml
security:
    providers:
        chain_provider:
            chain:
                providers: [main, fb_provider]
        main:
            entity: { class: AcmeBundle:User, property: username }
        fb_provider:
            id: facebook_user_provider

    firewalls:
        main:
            pattern:    ^/
            form_login:
                check_path: /login-check
                provider: main
            logout:     true
            anonymous:  true
            fos_facebook:
                check_path: /login-check-fb
                app_url: "http://apps.facebook.com/acme/"
                server_url: "http://acme.dev/app_dev.php/"
                provider: fb_provider
```

I guess it will trigger the rigth provider.
