### ISSUE TITLE
Remember me functionality is not working

### ISSUE THREAD

**Issue by WishCow** [FriendsOfSymfony/FOSFacebookBundle#276]
Having the following line in app/config/security.yml:

``` yaml
firewalls:
    my_area:
        fos_facebook:
            ...
            remember_me: true
            ...
```

I would expect a REMEMBERME cookie generated on facebook login, but unfortunately this does not happen. Is there some other way to keep the user logged in, after they have logged in facebook?
