### ISSUE TITLE
InvalidConfigurationException

### ISSUE THREAD

**Issue by bitraft** [FriendsOfSymfony/FOSFacebookBundle#98]
Follow the document, I got this :

InvalidConfigurationException: Invalid configuration for path "security.firewalls.public": The check_path "^/facebook/login_check$" for login method "fos_facebook" is not matched by the firewall pattern "^/facebook/.*".  

``` yml
        public:
            pattern:   ^/facebook/.*
            fos_facebook:
                login_path: ^/facebook/login
                check_path: ^/facebook/login_check$
                default_target_path: /mobile
                provider: my_fos_facebook_provider
            anonymous: true
            logout:
                handlers: ["fos_facebook.logout_handler"]
```
